export const blogPosts = [
    {
      id: 1,
      title: "Preparations for PyTorch and DirectML on AMD Ryzen 9 6950H for AI Projects",
      platform: "medium",
      link: "https://medium.com/@ochwada/preparations-for-pytorch-and-directml-on-amd-ryzen-9-6950h-for-ai-projects-15c164d22332",
      description: "Preparating for the Building Detection using PyTorch and DirectML on AMD Ryzen 9 6950H.",
      date: "2025-01-10",
    },
    {
      id: 2,
      title: "Preparing High-Resolution DOP from for Building Detection",
      platform: "medium",
      link: "https://medium.com/@ochwada/preparing-aerial-images-for-building-detection-using-the-dgm1-tiff-dataset-0317e804628f",
      description: "Explore how to prepare DOP data from OpenGeodata NRW for building detection.",
      date: "2025-01-01",
    },
    {
        id: 5,
        title: "Automated Retrieval and Exploration of SpaceNet 6 Dataset",
        platform: "medium",
        link: "https://medium.com/@ochwada/automated-data-access-and-exploration-ceb3eee1374c",
        description: "Downloading SpaceNet 6 dataset focusing on AOI 11 (Rotterdam),  using Python Scripts on AWS",
        date: "2024-12-30",
      },
      {
        id: 6,
        title: "Building Detection from Aerial Imagary: From Zero",
        platform: "medium",
        link: "https://medium.com/@ochwada/building-detection-from-aerial-imagary-from-zero-c4c4ef9f1ebf",
        description: "Develop a model that detects buildings from aerial imagery and converts the data into geospatial formats for usage in other applications e.g. urban planning, disaster assessment, smart city e.t.c.",
        date: "2024-12-30",
      },
    {
        id: 3,
        title: "SQL Basic Cheat Sheet",
        platform: "dev",
        link: "https://dev.to/ochwada/sql-basic-cheat-sheet-2fmm",
        description: "A quick reference guide covering the most commonly used SQL commands, syntax, and tips for beginners. Ideal for querying, filtering, and managing relational databases with ease.",
        date: "2022-04-30",
      },
      {
        id: 7,
        title: "Get Started with Face Detection with Python",
        platform: "dev",
        link: "https://dev.to/ochwada/get-started-with-face-detection-8o3",
        description: "Learn how to quickly implement face detection in Python using OpenCV. This guide covers essential techniques for beginners looking to explore computer vision.",
        date: "2022-05-01",
      },
      {
        id: 4,
        title: "2 Python Project Ideas for Beginners",
        platform: "dev",
        link: "https://dev.to/ochwada/2-python-project-ideas-for-beginners-d9a",
        description: "Two fun and beginner-friendly Python project ideas to help you practice real-world coding skills. Perfect for building confidence and strengthening your fundamentals.",
        date: "2022-05-01",
      },
  ];
  