

// -------------------------------------------Projects Navigation --------------------

export const projectsNavigation = [
    {
        id: " AuthenticationTripWise",
        name: "Authentication TripWise Application",
        description:"This is an Authentication microservice within the TripWise system, purpose-built for handling user authentication via OAuth2 with Google as the social login provider.",
        git_href: "https://github.com/Ochwada/TripWise-Pass",
        //web_href: " ",
        href: "https://github.com/Ochwada/TripWise-Pass/blob/main/README.md",
        image: '/assets/projects/code1.jpg',
        category: ["Backend & Data Eng."],
        subcategory: "Advanced Java",
        tools: ["#JWTAuthentication", "#SpringBoot", "#RESTfulAPI", "#Microservices", "#Docker"],
    },
    {
        id: " AuthenticationZalandoLiteV2",
        name: "Authentication ZalandoLite V2",
        description:"The Authentication Service, is a lightweight, modular microservice in the ZalandoLite ecosystem, purpose-built for handling user authentication via OAuth2 with Google as the social login provider.",
        git_href: "https://github.com/Ochwada/ZalandoLiteV2-authentication",
        //web_href: " ",
        href: "https://github.com/Ochwada/ZalandoLiteV2-authentication/blob/main/README.md",
        image: '/assets/projects/zalandoLite.jpg',
        category: ["Backend & Data Eng."],
        subcategory: "Advanced Java",
        tools: ["#JWTAuthentication", "#SpringBoot", "#RESTfulAPI", "#Microservices", "#Docker"],
    },
    {
        id: " ZalandoLiteV2",
        name: " ZalandoLite V2",
        description:"ZalandoLiteV2 is a microservices-based backend system simulating a fashion e-commerce platform. It includes seven (7) services, secured with Google OAuth2, containerized with Docker, and connected via the zalando-backend network. No UI—API only.",
        git_href: "https://github.com/Ochwada/ZalandoLiteV2-MicroservicesArchitecture",
        //web_href: " ",
        href: "https://github.com/Ochwada/ZalandoLiteV2-MicroservicesArchitecture/blob/main/README.md",
        image: '/assets/projects/code.jpg',
        category: ["Backend & Data Eng."],
        subcategory: "Advanced Java",
        tools: ["#JWTAuthentication", "#Database", "#SpringBoot", "#RESTfulAPI", "#Microservices"],
    },
    {
        id: "SecureJokeVault",
        name: "Secure Joke Vault",
        description:"A Spring Boot REST API for secure joke sharing with JWT-based authentication and MongoDB for persistent storage and supports easy deployment using Docker.",
        git_href: "https://github.com/Ochwada/Secure-Joke-Vault",
        //web_href: " ",
        href: "https://github.com/Ochwada/Secure-Joke-Vault/blob/main/README.md",
        image: '/assets/projects/code5.jpg',
        category: ["Backend & Data Eng."],
        subcategory: "Advanced Java",
        tools: ["#JWTAuthentication", "#MongoDB", "#SpringBoot", "#Docker", "#RESTfulAPI"],
    },
    {
        id: "ExpenseAssistant",
        name: "Expense Assistant App",
        description:"A full-stack Java REST API built with Spring Boot that helps travelers track their expenses globally. The app integrates real-time currency conversion (FreeCurrency API), live weather updates (OpenWeather API), and MongoDB for data persistence—fully containerized with Docker.",
        git_href: "https://github.com/Ochwada/ExpenseAssistant",
        //web_href: " ",
        href: "https://github.com/Ochwada/ExpenseAssistant/blob/main/README.md",
        image: '/assets/projects/code4.jpg',
        category: ["Backend & Data Eng."],
        subcategory: "Advanced Java",
        tools: ["#RESTfulAPI", "#MongoDB", "#SpringBoot", "#Docker"],
    },
    {
        id: "CurrencyConverter",
        name: "Currency Converter App",
        description:"A Currency Converter App using Spring Boot, designed to help users convert currencies in real-time using up-to-date exchange rates from an external API.",
        git_href: "https://github.com/Ochwada/CurrencyConverter-DemoApp",
        //web_href: " ",
        href: "https://github.com/Ochwada/CurrencyConverter-DemoApp/blob/main/README.md",
        image: '/assets/projects/code3.jpg',
        category: ["Backend & Data Eng."],
        subcategory: "Advanced Java",
        tools: ["#RESTfulAPI", "#MongoDB", "#SpringBoot", "#FreeCurrencyAPI" ],
    },
    {
        id: "TravelPlannerDemo",
        name: "Travel Planner App",
        description:"A Spring Boot-based RESTful API for planning travel itineraries and viewing weather forecasts. Provides endpoints for destination suggestions, itinerary management, and real-time weather integration.",
        git_href: "https://github.com/Ochwada/TravelPlannerDemo",
        //web_href: " ",
        href: "https://github.com/Ochwada/TravelPlannerDemo/blob/main/README.md",
        image: '/assets/projects/code2.jpg',
        category: ["Backend & Data Eng."],
        subcategory: "Advanced Java",
        tools: ["#RESTfulAPI", "#MongoDB", "#SpringBoot", "#OpenWeatherAPI" ],
    },
    {
        id: "HealthcareManagementSystem",
        name: " Healthcare Management System",
        description:"A Spring Boot application for managing healthcare entities such as patients, doctors, appointments, and medical records.",
        git_href: "https://github.com/Ochwada/HealthcareManagementSystem",
        //web_href: " ",
        href: "https://github.com/Ochwada/HealthcareManagementSystem/blob/main/README.md",
        image: '/assets/projects/code1.jpg',
        category: ["Backend & Data Eng."],
        subcategory: "Advanced Java",
        tools: ["#RESTfulAPI", "#MongoDB", "#SpringBoot" ],
    },
//{
        //id: "sql-hr-system",
        //name: "SQL Data System - HR System",
        //description: "An SQL-based project simulating an HR system — includes 50+ real-world queries on employees, departments, and salaries using advanced SQL features like JOINs, subqueries, window functions, and indexing for performance analysis.",
        //git_href: "https://github.com/Ochwada/JavaProjects-Springboot/blob/main/SQL%20Practice/070425_sql/070125_Selecting-Data-from-Relational-Databases.sql",
        // web_href: " ", // Add if you deploy or publish a live version
        //href: "https://github.com/Ochwada/JavaProjects-Springboot/blob/main/SQL%20Practice/070425_sql/README.md",
        //image: "/assets/projects/code.jpg",
        //category: ["Backend & Data Eng."],
        //subcategory: "SQL",
        //tools: [ "#psql" , "#SQL", "#pgAdmin", "#PostgreSQL"]
    // },
    /**{
        id: "SpringBoot",
        name: "SpringBoot - Mini Projects ",
        description:"A hands-on collection of Spring Boot mini-projects created during my transition from Core Java to modern backend engineering — showcasing REST APIs, data handling, and integration with industry-standard tools.",
        git_href: "https://github.com/Ochwada/JavaProjects-Springboot.git",
        //web_href: " ",
        href: "https://github.com/Ochwada/JavaProjects-Springboot/blob/main/README.md",
        image: '/assets/projects/springboot1.jpg',
        category: ["Backend & Data Eng."],
        subcategory: "Spring Boot",
        tools: ["#Java", "#intellijIDEA","#Maven", "#SpringBoot"],
    },*/
    {
        id: "ZalandoLite",
        name: "ZalandoLite - maven",
        description:"A minimalist backend service for the ZalandoLite mini project. Handles core functionalities like user management, product listings, and order processing in a simplified e-commerce setup.",
        git_href: "https://github.com/Ochwada/ZalandoLite_V0.git",
        //web_href: " ",
        href: "https://medium.com/@ochwada/my-first-java-mini-project-zalandolite-setup-structure-8b0da2e80fcd",
        image: '/assets/projects/zalandoLite.png',
        category: ["Backend & Data Eng."],
        subcategory: "Core Java",
        tools: ["#Java", "#intellijIDEA","#Maven"],
    },
    {
        id: "SmartSupplyChain",
        name: "Smart Supply Chain",
        description:"Mastering Generics, OOP, Collections, Maven, and JUnit 5",
        git_href: "https://github.com/Ochwada/JavaProjects/tree/main/00_Beginner_Projects(Data%20Structure)/beginner-SmartSupplyChain-v2",
        //web_href: " ",
        href: "https://github.com/Ochwada/JavaProjects/blob/main/00_Beginner_Projects(Data%20Structure)/beginner-SmartSupplyChain-v2/README.md",
        image: '/assets/projects/code.jpg',
        category: ["Backend & Data Eng."],
        subcategory: "Core Java",
        tools: ["#Java", "#intellijIDEA","#Maven"],
    },
    {
        id: "greenAreas",
        name: "Mapping Urban Green Space Accessibility (Berlin - Mitte)",
        git_href: "https://github.com/Ochwada/GeoSpatial-Projects/tree/main/Urban%20Green%20Space%20Accessibility%20Map",
        //web_href: " ",
        href: "https://medium.com/@ochwada/mapping-urban-green-space-accessibility-berlin-mitte-project-and-data-acquisition-in-python-62c2850a2d6e",
        image: '/assets/projects/accessibility3.png',
        category: ["Geo-Analytics"],
        subcategory: "Network Analysis",
        tools: ["#Python", "#Pycharm"],
    },
    /**{
        id: "javaProjects",
        name: "Core Java - Mini Projects ",
        description:"A collection of core Java projects. These projects demonstrate the use of OOP, collections, generics, file handling, and basic algorithms—laying a solid groundwork for enterprise-level development. ",
        git_href: "https://github.com/Ochwada/JavaProjects",
        //web_href: " ",
        href: "https://github.com/Ochwada/JavaProjects/blob/main/README.md",
        image: '/assets/projects/java.png',
        category: ["Backend & Data Eng."],
        subcategory: "Core Java",
        tools: ["#Java", "#intellijIDEA"],
    },*/
    {
        id: "portfolio25",
        name: "Portfolio - March 2025",
        git_href: "https://github.com/Ochwada/online_portfolio",
        web_href: "https://linda-ochwada.netlify.app/",
        href: "https://github.com/Ochwada/online_portfolio/blob/main/README.md",
        image: '/assets/present-port.png',
        category: ["Web Dev."],
        subcategory: "Frontend",
        tools: ["#React", "#TailwindCSS", "#NextJS", '#Netlify'],
    },
    {
        id: "ardhiapp",
        name: "Ardhi Project - WebGIS Application",
        git_href: "https://github.com/Ardhi-OWM/ardhi_supabase_clerk_latest",
        web_href: "https://ardhi-app.netlify.app/",
        href: "https://ardhi.slab.com/posts/what-is-ardhi-project-z0d01cz8?shr=EZiIPCLM0lt9h1C_2osUBQA_",
        image: '/assets/ardhi_app.png',
        category: ["Web Dev."],
        subcategory: "Geospatial Frontend",
        tools: ["#React", "#TailwindCSS", "#NextJS", '#Netlify'],
    },
    {
        id: "ardhi",
        name: "Ardhi Project - Landing Page",
        git_href: "https://github.com/Ardhi-OWM/landing-page-v2-2025",
        web_href: "https://ardhi.de/",
        href: "https://ardhi.slab.com/posts/what-is-ardhi-project-z0d01cz8?shr=EZiIPCLM0lt9h1C_2osUBQA_",
        image: '/assets/ardhi.png',
        category: ["Web Dev."],
        subcategory: "Frontend",
        tools: ["#React", "#TailwindCSS", "#Vite"],
    },
    {
        id: 'ProjectsProfile2023',
        name: "Portfolio - May 2023",
        git_href: "https://github.com/Ochwada/portfolios/tree/main/v2_2023/Ochwada_Profile_May2023",
        web_href: "https://ochwada-23.netlify.app/",
        href: "https://github.com/Ochwada/portfolios/blob/main/v2_2023/Ochwada_Profile_May2023/README.md",
        image: '/assets/profile0523.png',
        category: ["Web Dev."],
        subcategory: "Frontend",
        tools: ["#TailwindCSS", '#Netlify', "#React", "#Vite", "#ThreeJS", ],
    },
    {
        id: 'clvprediction',
        name: "Customer Lifetime Value Prediction",
        git_href: "https://github.com/Ochwada/Software_Code_Pytho",
        //web_href: "https://linda-ochwada.netlify.app/",
        href: "https://github.com/Ochwada/Software_Code_Pytho/blob/master/README.md",
        image: '/assets/clv.png',
        category: ["Data Science & ML"],
        subcategory: "Predictive Modeling",
        tools: ["#Python",],
    },
    {
        id: 'PhotosIntoCartoons1',
        name: "Turn Photos into Cartoons",
        git_href: "https://github.com/Ochwada/Data-Science-2023/blob/main/Photos%20into%20Cartoons/photo_to_catoons.ipynb",
        //web_href: "https://linda-ochwada.netlify.app/",
        href: "https://github.com/Ochwada/Data-Science-2023/blob/main/Photos%20into%20Cartoons/README.md",
        image: '/assets/catoon.png',
        category: ["Computer Vision"],
        subcategory: "Image Style Transfer",
        tools: ["#Python",],
    },
    {
        id: 'laphawp',
        name: "Location Analysis of Potential High Altitude Wind Power",
        git_href: "https://github.com/Ochwada/Thesis_-Data_Analysis-Public",
        //web_href: "https://linda-ochwada.netlify.app/",
        href: "https://medium.com/@ochwada/location-analysis-of-potential-high-altitude-wind-power-afcb37c275aa",
        image: '/assets/laphawp.png',
        category: ["Geo-Analytics"],
        subcategory: "Renewable Energy",
        tools: ["#Python",],
    },
];